name: Dev environment container deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  AZURE_WEBAPP_NAME: mtm-content-mgmt-web-app-dev
  IMAGE_NAME: mtm-content-mgmt-dev


permissions:
  id-token: write
#   contents: read
  
jobs:

          

  deploy:
    # needs: build
    runs-on: ubuntu-latest
    name: Deploy to Azure Web App
    steps:
      - name: Login to Azure
        uses: Azure/login@v1
        with:
          auth-type: 'SERVICE_PRINCIPAL'
          # creds: '{"clientId":"${{ secrets.AZ_CLIENT_ID }}","clientSecret":"${{ secrets.AZ_APP_REG_SECRET }}","subscriptionId":"${{ secrets.AZ_SUBSCRIPTION }}","tenantId":"${{ secrets.AZ_TENANT_ID }}"}'
          creds: ${{ secrets.AZ_CREDS }}
      - name: Azure CLI script test
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      
      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'mtm-content-mgmt-web-app-dev'
      #     slot-name: 'production'
      #     images: '${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest'    