# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Dev environment container depoyment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://mtmcontentmgmtacr.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_7cc2d4315c754db58e42c35495d53077 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_bce24d90150d4b5ba958a6026b50954f }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mtmcontentmgmtacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7cc2d4315c754db58e42c35495d53077 }}/mtm-content-mgmt:${{ github.sha }}
          file: ./src/mtm_admin/Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'development'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'mtm-content-mgmt-web-app-dev'
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_887ff2e59ca54aabbd58e9c2452a67b3 }}
            images: 'mtmcontentmgmtacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7cc2d4315c754db58e42c35495d53077 }}/mtm-content-mgmt:${{ github.sha }}'
