name: Dev environment container deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/mtm_admin
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://mtmcontentmgmtacr.azurecr.io/
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.AzureAppService_ContainerUsername_7cc2d4315c754db58e42c35495d53077 }}/mtm-content-mgmt:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mtm-content-mgmt-web-app-dev'
          slot-name: 'development'
          # publish-profile: ${{ secrets.AzureAppService_PublishProfile_887ff2e59ca54aabbd58e9c2452a67b3 }}
          images: '${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.ACR_USERNAME }}/mtm-content-mgmt:${{ github.sha }}'
