name: Dev environment container deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  AZURE_WEBAPP_NAME: mtm-content-mgmt-web-app-dev
  IMAGE_NAME: mtm-content-mgmt-dev
  AZ_SUBSCRIPTION_ID: bf7adf12-c3a8-426c-9976-29f145eba70f
  AZ_CLIENT_ID: 57f0c7c0-7edc-4ed6-b97c-28f39850d3d7
  AZ_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47


# permissions:
#   id-token: write
#   contents: read
  
jobs:
  # build:  
  #   runs-on: ubuntu-latest
  #   name: Build & push Docker image
  #   steps:
  #     - run: echo ${{ secrets.ACR_LOGIN_SERVER }}
  #     - uses: actions/checkout@v4
  #     - uses: mr-smithers-excellent/docker-build-push@v6
  #       with:
  #         directory: src/mtm_admin
  #         image: ${{ env.IMAGE_NAME }}
  #         # image: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}
  #         registry: ${{ secrets.ACR_LOGIN_SERVER }}
  #         dockerfile: src/mtm_admin/Dockerfile
  #         username: ${{ secrets.ACR_USERNAME }}
  #         password: ${{ secrets.ACR_PASSWORD }}
          
  
  deploy:
    name: Deploy to dev environment
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ env.AZ_CLIENT_ID }}","clientSecret":"${{ secrets.AZ_APP_REG_SECRET }}","subscriptionId":"${{ env.AZ_SUBSCRIPTION_ID }}","tenantId":"${{ env.AZ_TENANT_ID }}"}'
          # creds: '{"clientId":"${{ secrets.AZ_CLIENT_ID }}","clientSecret":"${{ secrets.AZ_APP_REG_SECRET }}","subscriptionId":"${{ secrets.AZ_SUBSCRIPTION }}","tenantId":"${{ secrets.AZ_TENANT_ID }}"}'
      
      - name: Azure CLI script test
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show