name: Dev environment container deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  AZURE_WEBAPP_NAME: mtm-content-mgmt-web-app-dev
  IMAGE_NAME: mtm-content-mgmt-dev

permissions:
  id-token: write
#   contents: read
  
jobs:

  build:  
    if: false
    runs-on: ubuntu-latest
    name: Build & push Docker image to ACR
    steps:
      - uses: actions/checkout@v4
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          directory: src/mtm_admin
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          dockerfile: src/mtm_admin/Dockerfile
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: echo ${{ env.IMAGE_NAME }}

  deploy:
    # needs: build
    runs-on: ubuntu-latest
    name: Deploy to Azure Web App
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          # creds: '{"clientId":"$ {{ secrets.AZ_CLIENT_ID }}","clientSecret":"$ {{ secrets.AZ_APP_REG_SECRET }}","subscriptionId":"$ {{ secrets.AZ_SUBSCRIPTION }}","tenantId":"$ {{ secrets.AZ_TENANT_ID }}"}'
          creds: ${{ secrets.AZ_CREDS }}

      - name: Azure CLI script test
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      # - name: Push from ACR to web app
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     slot-name: 'production'
      #     images: '${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest'


  

  